# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    {
-task: ServiceNow-DevOps-Server-Change-Acceleration@1,
        inputs: 
          connectedServiceName:'DevOps Connection',
          changeRequestDetails: 
            {
                "attributes": {
                  "requested_by": {
                    "user_name": "abel.tuter"        
                  },
                   "cmdb_ci": "b4fd7c8437201000deeabfc8bcbe5dc1",
                   "assignment_group": "a715cd759f2002002920bde8132e7018",
                   "start_date": "2021-01-05 08:00:00",
                   "end_date": "2021-01-08 08:00:00"
                }
              }
    }